name: Delete merged branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Delete merged branch
        run: |
          BRANCH="${{ github.event.pull_request.head.ref }}"
          echo "Deleting branch '$BRANCH' from remote"
          git push origin --delete "$BRANCH"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
